title: "僕が教室長を辞めたくなった100の言葉"
description: "もがき、苦しみ、工夫しながら生きた11年間の証。"
url: "https://tanamaru8.github.io"
baseurl: "/100-kotoba"

markdown: kramdown
kramdown:
  input: GFM

# _postsの記事は自動でlayout: postを適用する
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
